
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: clone_app_development

test:
  <<: *default
  database: clone_app_test

production:
  <<: *default
  database: clone_app_production
  username: clone_app
  password: <%= ENV['CLONE_APP_DATABASE_PASSWORD'] %>
